// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_service.proto

package gapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDeviceReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceReq) Reset()         { *m = GetDeviceReq{} }
func (m *GetDeviceReq) String() string { return proto.CompactTextString(m) }
func (*GetDeviceReq) ProtoMessage()    {}
func (*GetDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{0}
}

func (m *GetDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceReq.Unmarshal(m, b)
}
func (m *GetDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceReq.Marshal(b, m, deterministic)
}
func (m *GetDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceReq.Merge(m, src)
}
func (m *GetDeviceReq) XXX_Size() int {
	return xxx_messageInfo_GetDeviceReq.Size(m)
}
func (m *GetDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceReq proto.InternalMessageInfo

func (m *GetDeviceReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddDeviceReq struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeviceTypeId         string   `protobuf:"bytes,3,opt,name=device_type_id,json=deviceTypeId,proto3" json:"device_type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceReq) Reset()         { *m = AddDeviceReq{} }
func (m *AddDeviceReq) String() string { return proto.CompactTextString(m) }
func (*AddDeviceReq) ProtoMessage()    {}
func (*AddDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{1}
}

func (m *AddDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceReq.Unmarshal(m, b)
}
func (m *AddDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceReq.Marshal(b, m, deterministic)
}
func (m *AddDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceReq.Merge(m, src)
}
func (m *AddDeviceReq) XXX_Size() int {
	return xxx_messageInfo_AddDeviceReq.Size(m)
}
func (m *AddDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceReq proto.InternalMessageInfo

func (m *AddDeviceReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDeviceReq) GetDeviceTypeId() string {
	if m != nil {
		return m.DeviceTypeId
	}
	return ""
}

type AddDeviceRes struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceRes) Reset()         { *m = AddDeviceRes{} }
func (m *AddDeviceRes) String() string { return proto.CompactTextString(m) }
func (*AddDeviceRes) ProtoMessage()    {}
func (*AddDeviceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{2}
}

func (m *AddDeviceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceRes.Unmarshal(m, b)
}
func (m *AddDeviceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceRes.Marshal(b, m, deterministic)
}
func (m *AddDeviceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceRes.Merge(m, src)
}
func (m *AddDeviceRes) XXX_Size() int {
	return xxx_messageInfo_AddDeviceRes.Size(m)
}
func (m *AddDeviceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceRes proto.InternalMessageInfo

func (m *AddDeviceRes) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *AddDeviceRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateDeviceReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceReq) Reset()         { *m = UpdateDeviceReq{} }
func (m *UpdateDeviceReq) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceReq) ProtoMessage()    {}
func (*UpdateDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{3}
}

func (m *UpdateDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceReq.Unmarshal(m, b)
}
func (m *UpdateDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceReq.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceReq.Merge(m, src)
}
func (m *UpdateDeviceReq) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceReq.Size(m)
}
func (m *UpdateDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceReq proto.InternalMessageInfo

func (m *UpdateDeviceReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDeviceReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateDeviceRes struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceRes) Reset()         { *m = UpdateDeviceRes{} }
func (m *UpdateDeviceRes) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceRes) ProtoMessage()    {}
func (*UpdateDeviceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{4}
}

func (m *UpdateDeviceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceRes.Unmarshal(m, b)
}
func (m *UpdateDeviceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceRes.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceRes.Merge(m, src)
}
func (m *UpdateDeviceRes) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceRes.Size(m)
}
func (m *UpdateDeviceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceRes proto.InternalMessageInfo

func (m *UpdateDeviceRes) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type RemoveDeviceReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDeviceReq) Reset()         { *m = RemoveDeviceReq{} }
func (m *RemoveDeviceReq) String() string { return proto.CompactTextString(m) }
func (*RemoveDeviceReq) ProtoMessage()    {}
func (*RemoveDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{5}
}

func (m *RemoveDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDeviceReq.Unmarshal(m, b)
}
func (m *RemoveDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDeviceReq.Marshal(b, m, deterministic)
}
func (m *RemoveDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDeviceReq.Merge(m, src)
}
func (m *RemoveDeviceReq) XXX_Size() int {
	return xxx_messageInfo_RemoveDeviceReq.Size(m)
}
func (m *RemoveDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDeviceReq proto.InternalMessageInfo

func (m *RemoveDeviceReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveDeviceRes struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDeviceRes) Reset()         { *m = RemoveDeviceRes{} }
func (m *RemoveDeviceRes) String() string { return proto.CompactTextString(m) }
func (*RemoveDeviceRes) ProtoMessage()    {}
func (*RemoveDeviceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{6}
}

func (m *RemoveDeviceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDeviceRes.Unmarshal(m, b)
}
func (m *RemoveDeviceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDeviceRes.Marshal(b, m, deterministic)
}
func (m *RemoveDeviceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDeviceRes.Merge(m, src)
}
func (m *RemoveDeviceRes) XXX_Size() int {
	return xxx_messageInfo_RemoveDeviceRes.Size(m)
}
func (m *RemoveDeviceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDeviceRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDeviceRes proto.InternalMessageInfo

func (m *RemoveDeviceRes) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ListDevicesReq struct {
	Filter               *ListDevicesReq_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort                 *ListDevicesReq_Sort   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 *Page                  `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListDevicesReq) Reset()         { *m = ListDevicesReq{} }
func (m *ListDevicesReq) String() string { return proto.CompactTextString(m) }
func (*ListDevicesReq) ProtoMessage()    {}
func (*ListDevicesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{7}
}

func (m *ListDevicesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesReq.Unmarshal(m, b)
}
func (m *ListDevicesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesReq.Marshal(b, m, deterministic)
}
func (m *ListDevicesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesReq.Merge(m, src)
}
func (m *ListDevicesReq) XXX_Size() int {
	return xxx_messageInfo_ListDevicesReq.Size(m)
}
func (m *ListDevicesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesReq proto.InternalMessageInfo

func (m *ListDevicesReq) GetFilter() *ListDevicesReq_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListDevicesReq) GetSort() *ListDevicesReq_Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ListDevicesReq) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type ListDevicesReq_Filter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDevicesReq_Filter) Reset()         { *m = ListDevicesReq_Filter{} }
func (m *ListDevicesReq_Filter) String() string { return proto.CompactTextString(m) }
func (*ListDevicesReq_Filter) ProtoMessage()    {}
func (*ListDevicesReq_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{7, 0}
}

func (m *ListDevicesReq_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesReq_Filter.Unmarshal(m, b)
}
func (m *ListDevicesReq_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesReq_Filter.Marshal(b, m, deterministic)
}
func (m *ListDevicesReq_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesReq_Filter.Merge(m, src)
}
func (m *ListDevicesReq_Filter) XXX_Size() int {
	return xxx_messageInfo_ListDevicesReq_Filter.Size(m)
}
func (m *ListDevicesReq_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesReq_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesReq_Filter proto.InternalMessageInfo

func (m *ListDevicesReq_Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListDevicesReq_Filter) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListDevicesReq_Sort struct {
	Name                 SortDirection `protobuf:"varint,2,opt,name=name,proto3,enum=schema.SortDirection" json:"name,omitempty"`
	CreatedAt            SortDirection `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3,enum=schema.SortDirection" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDevicesReq_Sort) Reset()         { *m = ListDevicesReq_Sort{} }
func (m *ListDevicesReq_Sort) String() string { return proto.CompactTextString(m) }
func (*ListDevicesReq_Sort) ProtoMessage()    {}
func (*ListDevicesReq_Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{7, 1}
}

func (m *ListDevicesReq_Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesReq_Sort.Unmarshal(m, b)
}
func (m *ListDevicesReq_Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesReq_Sort.Marshal(b, m, deterministic)
}
func (m *ListDevicesReq_Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesReq_Sort.Merge(m, src)
}
func (m *ListDevicesReq_Sort) XXX_Size() int {
	return xxx_messageInfo_ListDevicesReq_Sort.Size(m)
}
func (m *ListDevicesReq_Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesReq_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesReq_Sort proto.InternalMessageInfo

func (m *ListDevicesReq_Sort) GetName() SortDirection {
	if m != nil {
		return m.Name
	}
	return SortDirection_NO_SORT
}

func (m *ListDevicesReq_Sort) GetCreatedAt() SortDirection {
	if m != nil {
		return m.CreatedAt
	}
	return SortDirection_NO_SORT
}

type ListDevicesRes struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListDevicesRes) Reset()         { *m = ListDevicesRes{} }
func (m *ListDevicesRes) String() string { return proto.CompactTextString(m) }
func (*ListDevicesRes) ProtoMessage()    {}
func (*ListDevicesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b575c291bff7431, []int{8}
}

func (m *ListDevicesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesRes.Unmarshal(m, b)
}
func (m *ListDevicesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesRes.Marshal(b, m, deterministic)
}
func (m *ListDevicesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesRes.Merge(m, src)
}
func (m *ListDevicesRes) XXX_Size() int {
	return xxx_messageInfo_ListDevicesRes.Size(m)
}
func (m *ListDevicesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesRes proto.InternalMessageInfo

func (m *ListDevicesRes) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDeviceReq)(nil), "schema.GetDeviceReq")
	proto.RegisterType((*AddDeviceReq)(nil), "schema.AddDeviceReq")
	proto.RegisterType((*AddDeviceRes)(nil), "schema.AddDeviceRes")
	proto.RegisterType((*UpdateDeviceReq)(nil), "schema.UpdateDeviceReq")
	proto.RegisterType((*UpdateDeviceRes)(nil), "schema.UpdateDeviceRes")
	proto.RegisterType((*RemoveDeviceReq)(nil), "schema.RemoveDeviceReq")
	proto.RegisterType((*RemoveDeviceRes)(nil), "schema.RemoveDeviceRes")
	proto.RegisterType((*ListDevicesReq)(nil), "schema.ListDevicesReq")
	proto.RegisterType((*ListDevicesReq_Filter)(nil), "schema.ListDevicesReq.Filter")
	proto.RegisterType((*ListDevicesReq_Sort)(nil), "schema.ListDevicesReq.Sort")
	proto.RegisterType((*ListDevicesRes)(nil), "schema.ListDevicesRes")
}

func init() { proto.RegisterFile("device_service.proto", fileDescriptor_5b575c291bff7431) }

var fileDescriptor_5b575c291bff7431 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x57, 0xb3, 0x90, 0xd1, 0xd7, 0x2c, 0x48, 0xd6, 0x60, 0x91, 0x11, 0xa8, 0x44, 0x1c, 0xca,
	0x25, 0x88, 0x42, 0x85, 0x84, 0x84, 0xc4, 0xd0, 0x04, 0x4c, 0xe2, 0x80, 0x32, 0xb8, 0x70, 0xa9,
	0x4c, 0xfd, 0xe8, 0xac, 0xad, 0x73, 0xb0, 0xcd, 0xa4, 0x7d, 0x35, 0x0e, 0x7c, 0xb6, 0x29, 0xb6,
	0x93, 0x66, 0x69, 0x72, 0x6a, 0xfd, 0x7e, 0xff, 0xac, 0xe7, 0x9f, 0x02, 0x87, 0x1c, 0xaf, 0xc5,
	0x0a, 0x97, 0x1a, 0x55, 0xf5, 0x9b, 0x97, 0x4a, 0x1a, 0x49, 0x22, 0xbd, 0x3a, 0xc7, 0x0d, 0xa3,
	0xb1, 0x43, 0xdd, 0x94, 0x1e, 0x9c, 0xe3, 0x65, 0x89, 0x4a, 0xbb, 0x63, 0xf6, 0x14, 0xe2, 0xcf,
	0x68, 0x4e, 0x2c, 0xa3, 0xc0, 0x3f, 0x24, 0x81, 0x40, 0xf0, 0x74, 0x34, 0x1d, 0xcd, 0xc6, 0x45,
	0x20, 0x78, 0xf6, 0x05, 0xe2, 0x63, 0xce, 0xb7, 0x38, 0x81, 0xf0, 0x8a, 0x6d, 0x30, 0x0d, 0x2c,
	0xc3, 0xfe, 0x27, 0xcf, 0x21, 0xf1, 0x17, 0x30, 0x37, 0x25, 0x2e, 0x05, 0x4f, 0xf7, 0x2c, 0xea,
	0x83, 0xbf, 0xdf, 0x94, 0x78, 0xca, 0xb3, 0xfc, 0x8e, 0x93, 0xae, 0x92, 0xe4, 0x85, 0x4d, 0xba,
	0x5f, 0x04, 0xf2, 0xc2, 0x27, 0x07, 0x4d, 0xf2, 0x02, 0x1e, 0xfc, 0x28, 0x39, 0x33, 0x38, 0x78,
	0xb9, 0xbe, 0xcb, 0x64, 0xcf, 0xba, 0xb2, 0x9d, 0xa4, 0x8a, 0x52, 0xe0, 0x46, 0x5e, 0x0f, 0x3b,
	0xef, 0x52, 0x76, 0x5d, 0xfe, 0x05, 0x90, 0x7c, 0x15, 0xda, 0xef, 0x4e, 0x57, 0x2e, 0x0b, 0x88,
	0x7e, 0x8b, 0x4b, 0x83, 0xca, 0xd2, 0x26, 0xf3, 0x27, 0xb9, 0x7b, 0x82, 0xfc, 0x2e, 0x2f, 0xff,
	0x64, 0x49, 0x85, 0x27, 0x93, 0x97, 0x10, 0x6a, 0xa9, 0x4c, 0x1a, 0x5a, 0xd1, 0xe3, 0x01, 0xd1,
	0x99, 0x54, 0xa6, 0xb0, 0x44, 0x32, 0x85, 0xb0, 0x64, 0x6b, 0x4c, 0xef, 0x59, 0x41, 0x5c, 0x0b,
	0xbe, 0xb1, 0x35, 0x16, 0x16, 0xa1, 0x0b, 0x88, 0x5c, 0x48, 0xb3, 0xa3, 0x51, 0xeb, 0xc1, 0x8e,
	0x60, 0xff, 0xaf, 0x46, 0xb5, 0x6c, 0xf6, 0x1d, 0x55, 0xc7, 0x53, 0x4e, 0xd7, 0x10, 0x56, 0x31,
	0xe4, 0x45, 0x6b, 0xb1, 0xc9, 0xfc, 0x61, 0x1d, 0x50, 0x61, 0x27, 0x42, 0xe1, 0xca, 0x08, 0x79,
	0xe5, 0xbd, 0xde, 0x00, 0xac, 0x14, 0x32, 0x83, 0x7c, 0xc9, 0x8c, 0x4d, 0x19, 0x14, 0x8c, 0x3d,
	0xf1, 0xd8, 0x64, 0xef, 0x3a, 0xbb, 0xd3, 0x64, 0x06, 0xfb, 0xae, 0x2e, 0x3a, 0x1d, 0x4d, 0xf7,
	0x66, 0x93, 0x79, 0x52, 0x9b, 0xf8, 0x27, 0xa8, 0xe1, 0xf9, 0xff, 0x00, 0x0e, 0xdc, 0xec, 0xcc,
	0xf5, 0x9d, 0xbc, 0x82, 0x71, 0x53, 0x62, 0x72, 0x58, 0xeb, 0xda, 0xbd, 0xa6, 0x1d, 0x37, 0xf2,
	0x16, 0xc6, 0x4d, 0x1b, 0xb7, 0x92, 0x76, 0xd5, 0x69, 0xdf, 0x54, 0x93, 0x0f, 0x10, 0xb7, 0xfb,
	0x45, 0x8e, 0x6a, 0x56, 0xa7, 0xac, 0x74, 0x00, 0xb0, 0x0e, 0xed, 0x6e, 0x6d, 0x1d, 0x3a, 0xa5,
	0xa4, 0x03, 0x80, 0x26, 0xef, 0x61, 0xd2, 0xda, 0x1e, 0x79, 0xd4, 0xdf, 0x18, 0xda, 0x3f, 0xd7,
	0x1f, 0xa3, 0x9f, 0xe1, 0x9a, 0x95, 0xe2, 0x57, 0x64, 0x3f, 0x01, 0xaf, 0x6f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x8e, 0x11, 0x52, 0xc4, 0x3f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceServiceClient interface {
	GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*Device, error)
	AddDevice(ctx context.Context, in *AddDeviceReq, opts ...grpc.CallOption) (*AddDeviceRes, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceReq, opts ...grpc.CallOption) (*UpdateDeviceRes, error)
	RemoveDevice(ctx context.Context, in *RemoveDeviceReq, opts ...grpc.CallOption) (*RemoveDeviceRes, error)
	ListDevices(ctx context.Context, in *ListDevicesReq, opts ...grpc.CallOption) (*ListDevicesRes, error)
}

type deviceServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceServiceClient(cc *grpc.ClientConn) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) GetDevice(ctx context.Context, in *GetDeviceReq, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := c.cc.Invoke(ctx, "/schema.DeviceService/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) AddDevice(ctx context.Context, in *AddDeviceReq, opts ...grpc.CallOption) (*AddDeviceRes, error) {
	out := new(AddDeviceRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceService/AddDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceReq, opts ...grpc.CallOption) (*UpdateDeviceRes, error) {
	out := new(UpdateDeviceRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceService/UpdateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) RemoveDevice(ctx context.Context, in *RemoveDeviceReq, opts ...grpc.CallOption) (*RemoveDeviceRes, error) {
	out := new(RemoveDeviceRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceService/RemoveDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) ListDevices(ctx context.Context, in *ListDevicesReq, opts ...grpc.CallOption) (*ListDevicesRes, error) {
	out := new(ListDevicesRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceService/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
type DeviceServiceServer interface {
	GetDevice(context.Context, *GetDeviceReq) (*Device, error)
	AddDevice(context.Context, *AddDeviceReq) (*AddDeviceRes, error)
	UpdateDevice(context.Context, *UpdateDeviceReq) (*UpdateDeviceRes, error)
	RemoveDevice(context.Context, *RemoveDeviceReq) (*RemoveDeviceRes, error)
	ListDevices(context.Context, *ListDevicesReq) (*ListDevicesRes, error)
}

// UnimplementedDeviceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceServiceServer struct {
}

func (*UnimplementedDeviceServiceServer) GetDevice(ctx context.Context, req *GetDeviceReq) (*Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (*UnimplementedDeviceServiceServer) AddDevice(ctx context.Context, req *AddDeviceReq) (*AddDeviceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDevice not implemented")
}
func (*UnimplementedDeviceServiceServer) UpdateDevice(ctx context.Context, req *UpdateDeviceReq) (*UpdateDeviceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (*UnimplementedDeviceServiceServer) RemoveDevice(ctx context.Context, req *RemoveDeviceReq) (*RemoveDeviceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDevice not implemented")
}
func (*UnimplementedDeviceServiceServer) ListDevices(ctx context.Context, req *ListDevicesReq) (*ListDevicesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}

func RegisterDeviceServiceServer(s *grpc.Server, srv DeviceServiceServer) {
	s.RegisterService(&_DeviceService_serviceDesc, srv)
}

func _DeviceService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceService/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDevice(ctx, req.(*GetDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceService/AddDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).AddDevice(ctx, req.(*AddDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceService/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_RemoveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RemoveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceService/RemoveDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RemoveDevice(ctx, req.(*RemoveDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceService/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ListDevices(ctx, req.(*ListDevicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevice",
			Handler:    _DeviceService_GetDevice_Handler,
		},
		{
			MethodName: "AddDevice",
			Handler:    _DeviceService_AddDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _DeviceService_UpdateDevice_Handler,
		},
		{
			MethodName: "RemoveDevice",
			Handler:    _DeviceService_RemoveDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _DeviceService_ListDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device_service.proto",
}
