// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_type_service.proto

package gapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDeviceTypeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceTypeReq) Reset()         { *m = GetDeviceTypeReq{} }
func (m *GetDeviceTypeReq) String() string { return proto.CompactTextString(m) }
func (*GetDeviceTypeReq) ProtoMessage()    {}
func (*GetDeviceTypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{0}
}

func (m *GetDeviceTypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceTypeReq.Unmarshal(m, b)
}
func (m *GetDeviceTypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceTypeReq.Marshal(b, m, deterministic)
}
func (m *GetDeviceTypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceTypeReq.Merge(m, src)
}
func (m *GetDeviceTypeReq) XXX_Size() int {
	return xxx_messageInfo_GetDeviceTypeReq.Size(m)
}
func (m *GetDeviceTypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceTypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceTypeReq proto.InternalMessageInfo

func (m *GetDeviceTypeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddDeviceTypeReq struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FlowDescriptorId     string   `protobuf:"bytes,4,opt,name=flow_descriptor_id,json=flowDescriptorId,proto3" json:"flow_descriptor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceTypeReq) Reset()         { *m = AddDeviceTypeReq{} }
func (m *AddDeviceTypeReq) String() string { return proto.CompactTextString(m) }
func (*AddDeviceTypeReq) ProtoMessage()    {}
func (*AddDeviceTypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{1}
}

func (m *AddDeviceTypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceTypeReq.Unmarshal(m, b)
}
func (m *AddDeviceTypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceTypeReq.Marshal(b, m, deterministic)
}
func (m *AddDeviceTypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceTypeReq.Merge(m, src)
}
func (m *AddDeviceTypeReq) XXX_Size() int {
	return xxx_messageInfo_AddDeviceTypeReq.Size(m)
}
func (m *AddDeviceTypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceTypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceTypeReq proto.InternalMessageInfo

func (m *AddDeviceTypeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDeviceTypeReq) GetFlowDescriptorId() string {
	if m != nil {
		return m.FlowDescriptorId
	}
	return ""
}

type AddDeviceTypeRes struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceTypeRes) Reset()         { *m = AddDeviceTypeRes{} }
func (m *AddDeviceTypeRes) String() string { return proto.CompactTextString(m) }
func (*AddDeviceTypeRes) ProtoMessage()    {}
func (*AddDeviceTypeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{2}
}

func (m *AddDeviceTypeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceTypeRes.Unmarshal(m, b)
}
func (m *AddDeviceTypeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceTypeRes.Marshal(b, m, deterministic)
}
func (m *AddDeviceTypeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceTypeRes.Merge(m, src)
}
func (m *AddDeviceTypeRes) XXX_Size() int {
	return xxx_messageInfo_AddDeviceTypeRes.Size(m)
}
func (m *AddDeviceTypeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceTypeRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceTypeRes proto.InternalMessageInfo

func (m *AddDeviceTypeRes) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *AddDeviceTypeRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateDeviceTypeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceTypeReq) Reset()         { *m = UpdateDeviceTypeReq{} }
func (m *UpdateDeviceTypeReq) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceTypeReq) ProtoMessage()    {}
func (*UpdateDeviceTypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{3}
}

func (m *UpdateDeviceTypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceTypeReq.Unmarshal(m, b)
}
func (m *UpdateDeviceTypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceTypeReq.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceTypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceTypeReq.Merge(m, src)
}
func (m *UpdateDeviceTypeReq) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceTypeReq.Size(m)
}
func (m *UpdateDeviceTypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceTypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceTypeReq proto.InternalMessageInfo

func (m *UpdateDeviceTypeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDeviceTypeReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateDeviceTypeRes struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceTypeRes) Reset()         { *m = UpdateDeviceTypeRes{} }
func (m *UpdateDeviceTypeRes) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceTypeRes) ProtoMessage()    {}
func (*UpdateDeviceTypeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{4}
}

func (m *UpdateDeviceTypeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceTypeRes.Unmarshal(m, b)
}
func (m *UpdateDeviceTypeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceTypeRes.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceTypeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceTypeRes.Merge(m, src)
}
func (m *UpdateDeviceTypeRes) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceTypeRes.Size(m)
}
func (m *UpdateDeviceTypeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceTypeRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceTypeRes proto.InternalMessageInfo

func (m *UpdateDeviceTypeRes) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type RemoveDeviceTypeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDeviceTypeReq) Reset()         { *m = RemoveDeviceTypeReq{} }
func (m *RemoveDeviceTypeReq) String() string { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeReq) ProtoMessage()    {}
func (*RemoveDeviceTypeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{5}
}

func (m *RemoveDeviceTypeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDeviceTypeReq.Unmarshal(m, b)
}
func (m *RemoveDeviceTypeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDeviceTypeReq.Marshal(b, m, deterministic)
}
func (m *RemoveDeviceTypeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDeviceTypeReq.Merge(m, src)
}
func (m *RemoveDeviceTypeReq) XXX_Size() int {
	return xxx_messageInfo_RemoveDeviceTypeReq.Size(m)
}
func (m *RemoveDeviceTypeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDeviceTypeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDeviceTypeReq proto.InternalMessageInfo

func (m *RemoveDeviceTypeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveDeviceTypeRes struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDeviceTypeRes) Reset()         { *m = RemoveDeviceTypeRes{} }
func (m *RemoveDeviceTypeRes) String() string { return proto.CompactTextString(m) }
func (*RemoveDeviceTypeRes) ProtoMessage()    {}
func (*RemoveDeviceTypeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{6}
}

func (m *RemoveDeviceTypeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDeviceTypeRes.Unmarshal(m, b)
}
func (m *RemoveDeviceTypeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDeviceTypeRes.Marshal(b, m, deterministic)
}
func (m *RemoveDeviceTypeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDeviceTypeRes.Merge(m, src)
}
func (m *RemoveDeviceTypeRes) XXX_Size() int {
	return xxx_messageInfo_RemoveDeviceTypeRes.Size(m)
}
func (m *RemoveDeviceTypeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDeviceTypeRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDeviceTypeRes proto.InternalMessageInfo

func (m *RemoveDeviceTypeRes) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ListDeviceTypesReq struct {
	Filter               *ListDeviceTypesReq_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort                 *ListDeviceTypesReq_Sort   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 *Page                      `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListDeviceTypesReq) Reset()         { *m = ListDeviceTypesReq{} }
func (m *ListDeviceTypesReq) String() string { return proto.CompactTextString(m) }
func (*ListDeviceTypesReq) ProtoMessage()    {}
func (*ListDeviceTypesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{7}
}

func (m *ListDeviceTypesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeviceTypesReq.Unmarshal(m, b)
}
func (m *ListDeviceTypesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeviceTypesReq.Marshal(b, m, deterministic)
}
func (m *ListDeviceTypesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeviceTypesReq.Merge(m, src)
}
func (m *ListDeviceTypesReq) XXX_Size() int {
	return xxx_messageInfo_ListDeviceTypesReq.Size(m)
}
func (m *ListDeviceTypesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeviceTypesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeviceTypesReq proto.InternalMessageInfo

func (m *ListDeviceTypesReq) GetFilter() *ListDeviceTypesReq_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListDeviceTypesReq) GetSort() *ListDeviceTypesReq_Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ListDeviceTypesReq) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type ListDeviceTypesReq_Filter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeviceTypesReq_Filter) Reset()         { *m = ListDeviceTypesReq_Filter{} }
func (m *ListDeviceTypesReq_Filter) String() string { return proto.CompactTextString(m) }
func (*ListDeviceTypesReq_Filter) ProtoMessage()    {}
func (*ListDeviceTypesReq_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{7, 0}
}

func (m *ListDeviceTypesReq_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeviceTypesReq_Filter.Unmarshal(m, b)
}
func (m *ListDeviceTypesReq_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeviceTypesReq_Filter.Marshal(b, m, deterministic)
}
func (m *ListDeviceTypesReq_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeviceTypesReq_Filter.Merge(m, src)
}
func (m *ListDeviceTypesReq_Filter) XXX_Size() int {
	return xxx_messageInfo_ListDeviceTypesReq_Filter.Size(m)
}
func (m *ListDeviceTypesReq_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeviceTypesReq_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeviceTypesReq_Filter proto.InternalMessageInfo

func (m *ListDeviceTypesReq_Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListDeviceTypesReq_Filter) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListDeviceTypesReq_Sort struct {
	Name                 SortDirection `protobuf:"varint,2,opt,name=name,proto3,enum=schema.SortDirection" json:"name,omitempty"`
	CreatedAt            SortDirection `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3,enum=schema.SortDirection" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDeviceTypesReq_Sort) Reset()         { *m = ListDeviceTypesReq_Sort{} }
func (m *ListDeviceTypesReq_Sort) String() string { return proto.CompactTextString(m) }
func (*ListDeviceTypesReq_Sort) ProtoMessage()    {}
func (*ListDeviceTypesReq_Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{7, 1}
}

func (m *ListDeviceTypesReq_Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeviceTypesReq_Sort.Unmarshal(m, b)
}
func (m *ListDeviceTypesReq_Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeviceTypesReq_Sort.Marshal(b, m, deterministic)
}
func (m *ListDeviceTypesReq_Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeviceTypesReq_Sort.Merge(m, src)
}
func (m *ListDeviceTypesReq_Sort) XXX_Size() int {
	return xxx_messageInfo_ListDeviceTypesReq_Sort.Size(m)
}
func (m *ListDeviceTypesReq_Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeviceTypesReq_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeviceTypesReq_Sort proto.InternalMessageInfo

func (m *ListDeviceTypesReq_Sort) GetName() SortDirection {
	if m != nil {
		return m.Name
	}
	return SortDirection_NO_SORT
}

func (m *ListDeviceTypesReq_Sort) GetCreatedAt() SortDirection {
	if m != nil {
		return m.CreatedAt
	}
	return SortDirection_NO_SORT
}

type ListDeviceTypesRes struct {
	DeviceTypes          []*DeviceType `protobuf:"bytes,1,rep,name=device_types,json=deviceTypes,proto3" json:"device_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDeviceTypesRes) Reset()         { *m = ListDeviceTypesRes{} }
func (m *ListDeviceTypesRes) String() string { return proto.CompactTextString(m) }
func (*ListDeviceTypesRes) ProtoMessage()    {}
func (*ListDeviceTypesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ec6dee971d7020, []int{8}
}

func (m *ListDeviceTypesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeviceTypesRes.Unmarshal(m, b)
}
func (m *ListDeviceTypesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeviceTypesRes.Marshal(b, m, deterministic)
}
func (m *ListDeviceTypesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeviceTypesRes.Merge(m, src)
}
func (m *ListDeviceTypesRes) XXX_Size() int {
	return xxx_messageInfo_ListDeviceTypesRes.Size(m)
}
func (m *ListDeviceTypesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeviceTypesRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeviceTypesRes proto.InternalMessageInfo

func (m *ListDeviceTypesRes) GetDeviceTypes() []*DeviceType {
	if m != nil {
		return m.DeviceTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDeviceTypeReq)(nil), "schema.GetDeviceTypeReq")
	proto.RegisterType((*AddDeviceTypeReq)(nil), "schema.AddDeviceTypeReq")
	proto.RegisterType((*AddDeviceTypeRes)(nil), "schema.AddDeviceTypeRes")
	proto.RegisterType((*UpdateDeviceTypeReq)(nil), "schema.UpdateDeviceTypeReq")
	proto.RegisterType((*UpdateDeviceTypeRes)(nil), "schema.UpdateDeviceTypeRes")
	proto.RegisterType((*RemoveDeviceTypeReq)(nil), "schema.RemoveDeviceTypeReq")
	proto.RegisterType((*RemoveDeviceTypeRes)(nil), "schema.RemoveDeviceTypeRes")
	proto.RegisterType((*ListDeviceTypesReq)(nil), "schema.ListDeviceTypesReq")
	proto.RegisterType((*ListDeviceTypesReq_Filter)(nil), "schema.ListDeviceTypesReq.Filter")
	proto.RegisterType((*ListDeviceTypesReq_Sort)(nil), "schema.ListDeviceTypesReq.Sort")
	proto.RegisterType((*ListDeviceTypesRes)(nil), "schema.ListDeviceTypesRes")
}

func init() { proto.RegisterFile("device_type_service.proto", fileDescriptor_64ec6dee971d7020) }

var fileDescriptor_64ec6dee971d7020 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x57, 0x43, 0x08, 0xec, 0x75, 0x1d, 0xdd, 0x43, 0x88, 0x60, 0x0e, 0x94, 0x48, 0x48, 0x43,
	0x42, 0x3d, 0x64, 0xec, 0xb0, 0x03, 0x87, 0x41, 0x05, 0xaa, 0xd8, 0x01, 0x65, 0xe3, 0xc2, 0x25,
	0x0a, 0xf1, 0x5b, 0x67, 0xad, 0x9d, 0x83, 0x6d, 0x86, 0xf6, 0x05, 0xf9, 0x58, 0x08, 0xd9, 0x69,
	0xda, 0x34, 0x4d, 0x73, 0x8b, 0xf5, 0xfb, 0xf7, 0xf4, 0xfe, 0x04, 0x5e, 0x70, 0xba, 0x13, 0x39,
	0xa5, 0xe6, 0xbe, 0xa0, 0x54, 0x93, 0xb2, 0x8f, 0x71, 0xa1, 0xa4, 0x91, 0x18, 0xe8, 0xfc, 0x9a,
	0x16, 0x19, 0x3b, 0xac, 0x51, 0x4a, 0x88, 0x0d, 0xae, 0x69, 0x5e, 0x90, 0xd2, 0xe5, 0x33, 0x8a,
	0x60, 0xf8, 0x85, 0xcc, 0xc4, 0xd1, 0x2e, 0xef, 0x0b, 0x4a, 0xe8, 0x17, 0x1e, 0x80, 0x27, 0x78,
	0xd8, 0x1b, 0xf5, 0x8e, 0xf6, 0x12, 0x4f, 0xf0, 0xe8, 0x12, 0x86, 0x67, 0x9c, 0x6f, 0x72, 0x10,
	0xfc, 0xdb, 0x6c, 0x41, 0xa1, 0xe7, 0x58, 0xee, 0x1b, 0xdf, 0x01, 0x5e, 0xcd, 0xe5, 0x9f, 0x94,
	0x93, 0xce, 0x95, 0x28, 0x8c, 0x54, 0xa9, 0xe0, 0xa1, 0xef, 0x18, 0x43, 0x8b, 0x4c, 0x56, 0xc0,
	0x94, 0x47, 0xf1, 0x96, 0xab, 0xb6, 0xc9, 0xf2, 0xc6, 0x25, 0x3f, 0x4e, 0x3c, 0x79, 0xb3, 0xac,
	0xc4, 0x5b, 0x55, 0x72, 0x0a, 0x4f, 0xbf, 0x17, 0x3c, 0x33, 0xd4, 0x59, 0x70, 0x5b, 0x71, 0xd1,
	0x9b, 0x36, 0xe9, 0x56, 0xa2, 0xa5, 0x25, 0xb4, 0x90, 0x77, 0xdd, 0x09, 0xed, 0xb4, 0x6d, 0xb7,
	0xbf, 0x1e, 0xe0, 0xb9, 0xd0, 0xb5, 0xfe, 0x6a, 0xeb, 0x76, 0x0a, 0xc1, 0x95, 0x98, 0x1b, 0x52,
	0x8e, 0xda, 0x8f, 0x5f, 0x8f, 0xcb, 0x79, 0x8d, 0xb7, 0xb9, 0xe3, 0xcf, 0x8e, 0x98, 0x2c, 0x05,
	0x78, 0x0c, 0xbe, 0x96, 0xca, 0xb8, 0xae, 0xf6, 0xe3, 0x57, 0x1d, 0xc2, 0x0b, 0xa9, 0x4c, 0xe2,
	0xc8, 0x38, 0x02, 0xbf, 0xc8, 0x66, 0x14, 0x3e, 0x74, 0xa2, 0xfd, 0x4a, 0xf4, 0x2d, 0x9b, 0x51,
	0xe2, 0x10, 0x76, 0x02, 0x41, 0x19, 0xb4, 0xea, 0x5d, 0xaf, 0x36, 0xd8, 0xe7, 0xf0, 0xe8, 0xb7,
	0x26, 0x37, 0xcd, 0xb2, 0xa5, 0x81, 0x7d, 0x4e, 0x39, 0x9b, 0x81, 0x6f, 0x63, 0xf0, 0x6d, 0xad,
	0xe1, 0x07, 0xf1, 0xb3, 0x2a, 0xc0, 0x62, 0x13, 0xa1, 0x28, 0x37, 0x42, 0xde, 0x2e, 0xbd, 0xde,
	0x03, 0xe4, 0x8a, 0x32, 0x43, 0x3c, 0xcd, 0x8c, 0x4b, 0xd9, 0x29, 0xd8, 0x5b, 0x12, 0xcf, 0x4c,
	0xf4, 0xb5, 0xa5, 0x8f, 0x1a, 0x4f, 0x60, 0xbf, 0xb6, 0xe0, 0x3a, 0xec, 0x8d, 0x1e, 0x1c, 0xf5,
	0x63, 0xac, 0xdc, 0x6a, 0xb3, 0xe9, 0xf3, 0xb5, 0x32, 0xfe, 0xe7, 0xc1, 0xe1, 0x1a, 0xbb, 0x28,
	0x2f, 0x07, 0x3f, 0xc0, 0x60, 0xe3, 0x12, 0x30, 0xac, 0x7c, 0x9a, 0x07, 0xc2, 0x5a, 0x12, 0xf0,
	0x13, 0x0c, 0x36, 0xd6, 0x79, 0x2d, 0x6f, 0xde, 0x0e, 0xdb, 0x85, 0x68, 0x3c, 0x87, 0x61, 0x73,
	0x49, 0xf1, 0x65, 0xc5, 0x6e, 0xd9, 0x7c, 0xd6, 0x01, 0x3a, 0xb7, 0xe6, 0x92, 0xae, 0xdd, 0x5a,
	0xb6, 0x9c, 0x75, 0x80, 0x1a, 0xa7, 0xf0, 0xa4, 0x31, 0x02, 0x64, 0xbb, 0xd7, 0x8f, 0xed, 0xc6,
	0xf4, 0xc7, 0xe0, 0x87, 0x3f, 0xcb, 0x0a, 0xf1, 0x33, 0x70, 0xff, 0xa0, 0xe3, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x55, 0xdf, 0x93, 0x07, 0xca, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceTypeServiceClient is the client API for DeviceTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceTypeServiceClient interface {
	GetDeviceType(ctx context.Context, in *GetDeviceTypeReq, opts ...grpc.CallOption) (*DeviceType, error)
	AddDeviceType(ctx context.Context, in *AddDeviceTypeReq, opts ...grpc.CallOption) (*AddDeviceTypeRes, error)
	UpdateDeviceType(ctx context.Context, in *UpdateDeviceTypeReq, opts ...grpc.CallOption) (*UpdateDeviceTypeRes, error)
	RemoveDeviceType(ctx context.Context, in *RemoveDeviceTypeReq, opts ...grpc.CallOption) (*RemoveDeviceTypeRes, error)
	ListDeviceTypes(ctx context.Context, in *ListDeviceTypesReq, opts ...grpc.CallOption) (*ListDeviceTypesRes, error)
}

type deviceTypeServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceTypeServiceClient(cc *grpc.ClientConn) DeviceTypeServiceClient {
	return &deviceTypeServiceClient{cc}
}

func (c *deviceTypeServiceClient) GetDeviceType(ctx context.Context, in *GetDeviceTypeReq, opts ...grpc.CallOption) (*DeviceType, error) {
	out := new(DeviceType)
	err := c.cc.Invoke(ctx, "/schema.DeviceTypeService/GetDeviceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTypeServiceClient) AddDeviceType(ctx context.Context, in *AddDeviceTypeReq, opts ...grpc.CallOption) (*AddDeviceTypeRes, error) {
	out := new(AddDeviceTypeRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceTypeService/AddDeviceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTypeServiceClient) UpdateDeviceType(ctx context.Context, in *UpdateDeviceTypeReq, opts ...grpc.CallOption) (*UpdateDeviceTypeRes, error) {
	out := new(UpdateDeviceTypeRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceTypeService/UpdateDeviceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTypeServiceClient) RemoveDeviceType(ctx context.Context, in *RemoveDeviceTypeReq, opts ...grpc.CallOption) (*RemoveDeviceTypeRes, error) {
	out := new(RemoveDeviceTypeRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceTypeService/RemoveDeviceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTypeServiceClient) ListDeviceTypes(ctx context.Context, in *ListDeviceTypesReq, opts ...grpc.CallOption) (*ListDeviceTypesRes, error) {
	out := new(ListDeviceTypesRes)
	err := c.cc.Invoke(ctx, "/schema.DeviceTypeService/ListDeviceTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceTypeServiceServer is the server API for DeviceTypeService service.
type DeviceTypeServiceServer interface {
	GetDeviceType(context.Context, *GetDeviceTypeReq) (*DeviceType, error)
	AddDeviceType(context.Context, *AddDeviceTypeReq) (*AddDeviceTypeRes, error)
	UpdateDeviceType(context.Context, *UpdateDeviceTypeReq) (*UpdateDeviceTypeRes, error)
	RemoveDeviceType(context.Context, *RemoveDeviceTypeReq) (*RemoveDeviceTypeRes, error)
	ListDeviceTypes(context.Context, *ListDeviceTypesReq) (*ListDeviceTypesRes, error)
}

// UnimplementedDeviceTypeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceTypeServiceServer struct {
}

func (*UnimplementedDeviceTypeServiceServer) GetDeviceType(ctx context.Context, req *GetDeviceTypeReq) (*DeviceType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceType not implemented")
}
func (*UnimplementedDeviceTypeServiceServer) AddDeviceType(ctx context.Context, req *AddDeviceTypeReq) (*AddDeviceTypeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeviceType not implemented")
}
func (*UnimplementedDeviceTypeServiceServer) UpdateDeviceType(ctx context.Context, req *UpdateDeviceTypeReq) (*UpdateDeviceTypeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeviceType not implemented")
}
func (*UnimplementedDeviceTypeServiceServer) RemoveDeviceType(ctx context.Context, req *RemoveDeviceTypeReq) (*RemoveDeviceTypeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDeviceType not implemented")
}
func (*UnimplementedDeviceTypeServiceServer) ListDeviceTypes(ctx context.Context, req *ListDeviceTypesReq) (*ListDeviceTypesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeviceTypes not implemented")
}

func RegisterDeviceTypeServiceServer(s *grpc.Server, srv DeviceTypeServiceServer) {
	s.RegisterService(&_DeviceTypeService_serviceDesc, srv)
}

func _DeviceTypeService_GetDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTypeServiceServer).GetDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceTypeService/GetDeviceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTypeServiceServer).GetDeviceType(ctx, req.(*GetDeviceTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTypeService_AddDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTypeServiceServer).AddDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceTypeService/AddDeviceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTypeServiceServer).AddDeviceType(ctx, req.(*AddDeviceTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTypeService_UpdateDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTypeServiceServer).UpdateDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceTypeService/UpdateDeviceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTypeServiceServer).UpdateDeviceType(ctx, req.(*UpdateDeviceTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTypeService_RemoveDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeviceTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTypeServiceServer).RemoveDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceTypeService/RemoveDeviceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTypeServiceServer).RemoveDeviceType(ctx, req.(*RemoveDeviceTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTypeService_ListDeviceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceTypesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTypeServiceServer).ListDeviceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.DeviceTypeService/ListDeviceTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTypeServiceServer).ListDeviceTypes(ctx, req.(*ListDeviceTypesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceTypeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.DeviceTypeService",
	HandlerType: (*DeviceTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceType",
			Handler:    _DeviceTypeService_GetDeviceType_Handler,
		},
		{
			MethodName: "AddDeviceType",
			Handler:    _DeviceTypeService_AddDeviceType_Handler,
		},
		{
			MethodName: "UpdateDeviceType",
			Handler:    _DeviceTypeService_UpdateDeviceType_Handler,
		},
		{
			MethodName: "RemoveDeviceType",
			Handler:    _DeviceTypeService_RemoveDeviceType_Handler,
		},
		{
			MethodName: "ListDeviceTypes",
			Handler:    _DeviceTypeService_ListDeviceTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device_type_service.proto",
}
