// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device-type.proto

package gapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceType struct {
	ID                   string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FlowDescriptorID     string    `protobuf:"bytes,4,opt,name=flowDescriptorID,proto3" json:"flowDescriptorID,omitempty"`
	UserID               string    `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	CreatedAt            *UnixTime `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeviceType) Reset()         { *m = DeviceType{} }
func (m *DeviceType) String() string { return proto.CompactTextString(m) }
func (*DeviceType) ProtoMessage()    {}
func (*DeviceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9a3fa46358cd5c, []int{0}
}

func (m *DeviceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceType.Unmarshal(m, b)
}
func (m *DeviceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceType.Marshal(b, m, deterministic)
}
func (m *DeviceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceType.Merge(m, src)
}
func (m *DeviceType) XXX_Size() int {
	return xxx_messageInfo_DeviceType.Size(m)
}
func (m *DeviceType) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceType.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceType proto.InternalMessageInfo

func (m *DeviceType) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceType) GetFlowDescriptorID() string {
	if m != nil {
		return m.FlowDescriptorID
	}
	return ""
}

func (m *DeviceType) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeviceType) GetCreatedAt() *UnixTime {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceType)(nil), "schema.DeviceType")
}

func init() { proto.RegisterFile("device-type.proto", fileDescriptor_fe9a3fa46358cd5c) }

var fileDescriptor_fe9a3fa46358cd5c = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2d, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b,
	0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x94, 0xe2, 0x2f, 0xcd, 0xcb, 0xac, 0xd0, 0x2d, 0xc9, 0xcc, 0x85,
	0x4a, 0x28, 0x2d, 0x61, 0xe4, 0xe2, 0x72, 0x01, 0x2b, 0x0f, 0xa9, 0x2c, 0x48, 0x15, 0xe2, 0xe3,
	0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xf2, 0x74, 0x11, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x80, 0xd9, 0x42, 0x5a, 0x5c, 0x02, 0x69,
	0x39, 0xf9, 0xe5, 0x2e, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05, 0x25, 0xf9, 0x45, 0x9e, 0x2e, 0x12,
	0x2c, 0x60, 0x79, 0x0c, 0x71, 0x21, 0x31, 0x2e, 0xb6, 0xd2, 0xe2, 0x54, 0x90, 0x0a, 0x66, 0xb0,
	0x0a, 0x28, 0x4f, 0x48, 0x8f, 0x8b, 0x33, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x35, 0xc5, 0xb1, 0x44,
	0x82, 0x55, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x40, 0x0f, 0xe2, 0x46, 0xbd, 0xd0, 0xbc, 0xcc, 0x8a,
	0x90, 0xcc, 0xdc, 0xd4, 0x20, 0x84, 0x12, 0x27, 0xb6, 0x28, 0x96, 0xf4, 0xc4, 0x82, 0xcc, 0x24,
	0x36, 0xb0, 0xab, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0x10, 0x75, 0xab, 0xe3, 0x00,
	0x00, 0x00,
}
