// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipe.proto

package gapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pipe struct {
	ID                   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PipeDescriptorID     string            `protobuf:"bytes,2,opt,name=pipeDescriptorID,proto3" json:"pipeDescriptorID,omitempty"`
	Params               map[string]*Value `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Binds                []*PipeBind       `protobuf:"bytes,4,rep,name=binds,proto3" json:"binds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Pipe) Reset()         { *m = Pipe{} }
func (m *Pipe) String() string { return proto.CompactTextString(m) }
func (*Pipe) ProtoMessage()    {}
func (*Pipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1979e1a5fdc07ed, []int{0}
}

func (m *Pipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipe.Unmarshal(m, b)
}
func (m *Pipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipe.Marshal(b, m, deterministic)
}
func (m *Pipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipe.Merge(m, src)
}
func (m *Pipe) XXX_Size() int {
	return xxx_messageInfo_Pipe.Size(m)
}
func (m *Pipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipe.DiscardUnknown(m)
}

var xxx_messageInfo_Pipe proto.InternalMessageInfo

func (m *Pipe) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Pipe) GetPipeDescriptorID() string {
	if m != nil {
		return m.PipeDescriptorID
	}
	return ""
}

func (m *Pipe) GetParams() map[string]*Value {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Pipe) GetBinds() []*PipeBind {
	if m != nil {
		return m.Binds
	}
	return nil
}

type PipeBind struct {
	FromOutputID         string   `protobuf:"bytes,1,opt,name=fromOutputID,proto3" json:"fromOutputID,omitempty"`
	ToPipeID             string   `protobuf:"bytes,2,opt,name=toPipeID,proto3" json:"toPipeID,omitempty"`
	ToInputID            string   `protobuf:"bytes,3,opt,name=toInputID,proto3" json:"toInputID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipeBind) Reset()         { *m = PipeBind{} }
func (m *PipeBind) String() string { return proto.CompactTextString(m) }
func (*PipeBind) ProtoMessage()    {}
func (*PipeBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1979e1a5fdc07ed, []int{1}
}

func (m *PipeBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipeBind.Unmarshal(m, b)
}
func (m *PipeBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipeBind.Marshal(b, m, deterministic)
}
func (m *PipeBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipeBind.Merge(m, src)
}
func (m *PipeBind) XXX_Size() int {
	return xxx_messageInfo_PipeBind.Size(m)
}
func (m *PipeBind) XXX_DiscardUnknown() {
	xxx_messageInfo_PipeBind.DiscardUnknown(m)
}

var xxx_messageInfo_PipeBind proto.InternalMessageInfo

func (m *PipeBind) GetFromOutputID() string {
	if m != nil {
		return m.FromOutputID
	}
	return ""
}

func (m *PipeBind) GetToPipeID() string {
	if m != nil {
		return m.ToPipeID
	}
	return ""
}

func (m *PipeBind) GetToInputID() string {
	if m != nil {
		return m.ToInputID
	}
	return ""
}

type PipeExt struct {
	ID                   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PipeDescriptorID     string            `protobuf:"bytes,2,opt,name=pipeDescriptorID,proto3" json:"pipeDescriptorID,omitempty"`
	Params               map[string]*Value `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Binds                []*PipeBindExt    `protobuf:"bytes,5,rep,name=binds,proto3" json:"binds,omitempty"`
	PluginURI            string            `protobuf:"bytes,6,opt,name=pluginURI,proto3" json:"pluginURI,omitempty"`
	FlowID               string            `protobuf:"bytes,7,opt,name=flowID,proto3" json:"flowID,omitempty"`
	PipeDescriptorName   string            `protobuf:"bytes,8,opt,name=pipeDescriptorName,proto3" json:"pipeDescriptorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PipeExt) Reset()         { *m = PipeExt{} }
func (m *PipeExt) String() string { return proto.CompactTextString(m) }
func (*PipeExt) ProtoMessage()    {}
func (*PipeExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1979e1a5fdc07ed, []int{2}
}

func (m *PipeExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipeExt.Unmarshal(m, b)
}
func (m *PipeExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipeExt.Marshal(b, m, deterministic)
}
func (m *PipeExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipeExt.Merge(m, src)
}
func (m *PipeExt) XXX_Size() int {
	return xxx_messageInfo_PipeExt.Size(m)
}
func (m *PipeExt) XXX_DiscardUnknown() {
	xxx_messageInfo_PipeExt.DiscardUnknown(m)
}

var xxx_messageInfo_PipeExt proto.InternalMessageInfo

func (m *PipeExt) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PipeExt) GetPipeDescriptorID() string {
	if m != nil {
		return m.PipeDescriptorID
	}
	return ""
}

func (m *PipeExt) GetParams() map[string]*Value {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PipeExt) GetBinds() []*PipeBindExt {
	if m != nil {
		return m.Binds
	}
	return nil
}

func (m *PipeExt) GetPluginURI() string {
	if m != nil {
		return m.PluginURI
	}
	return ""
}

func (m *PipeExt) GetFlowID() string {
	if m != nil {
		return m.FlowID
	}
	return ""
}

func (m *PipeExt) GetPipeDescriptorName() string {
	if m != nil {
		return m.PipeDescriptorName
	}
	return ""
}

type PipeBindExt struct {
	FromOutputID         string   `protobuf:"bytes,1,opt,name=fromOutputID,proto3" json:"fromOutputID,omitempty"`
	ToPipeID             string   `protobuf:"bytes,2,opt,name=toPipeID,proto3" json:"toPipeID,omitempty"`
	ToPipe               *PipeExt `protobuf:"bytes,4,opt,name=toPipe,proto3" json:"toPipe,omitempty"`
	ToInputID            string   `protobuf:"bytes,3,opt,name=toInputID,proto3" json:"toInputID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipeBindExt) Reset()         { *m = PipeBindExt{} }
func (m *PipeBindExt) String() string { return proto.CompactTextString(m) }
func (*PipeBindExt) ProtoMessage()    {}
func (*PipeBindExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1979e1a5fdc07ed, []int{3}
}

func (m *PipeBindExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipeBindExt.Unmarshal(m, b)
}
func (m *PipeBindExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipeBindExt.Marshal(b, m, deterministic)
}
func (m *PipeBindExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipeBindExt.Merge(m, src)
}
func (m *PipeBindExt) XXX_Size() int {
	return xxx_messageInfo_PipeBindExt.Size(m)
}
func (m *PipeBindExt) XXX_DiscardUnknown() {
	xxx_messageInfo_PipeBindExt.DiscardUnknown(m)
}

var xxx_messageInfo_PipeBindExt proto.InternalMessageInfo

func (m *PipeBindExt) GetFromOutputID() string {
	if m != nil {
		return m.FromOutputID
	}
	return ""
}

func (m *PipeBindExt) GetToPipeID() string {
	if m != nil {
		return m.ToPipeID
	}
	return ""
}

func (m *PipeBindExt) GetToPipe() *PipeExt {
	if m != nil {
		return m.ToPipe
	}
	return nil
}

func (m *PipeBindExt) GetToInputID() string {
	if m != nil {
		return m.ToInputID
	}
	return ""
}

func init() {
	proto.RegisterType((*Pipe)(nil), "schema.Pipe")
	proto.RegisterMapType((map[string]*Value)(nil), "schema.Pipe.ParamsEntry")
	proto.RegisterType((*PipeBind)(nil), "schema.PipeBind")
	proto.RegisterType((*PipeExt)(nil), "schema.PipeExt")
	proto.RegisterMapType((map[string]*Value)(nil), "schema.PipeExt.ParamsEntry")
	proto.RegisterType((*PipeBindExt)(nil), "schema.PipeBindExt")
}

func init() { proto.RegisterFile("pipe.proto", fileDescriptor_d1979e1a5fdc07ed) }

var fileDescriptor_d1979e1a5fdc07ed = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x4d, 0x7f, 0x28, 0x70, 0xfb, 0x7d, 0x4a, 0xc6, 0xc4, 0x4c, 0xd0, 0x05, 0xa9, 0x89, 0xa2,
	0x8b, 0xc6, 0xc0, 0xc6, 0xb8, 0x24, 0x6d, 0x62, 0x37, 0x4a, 0x9a, 0xe8, 0xc2, 0x5d, 0x81, 0x02,
	0x8d, 0xb4, 0x33, 0x69, 0xa7, 0x0a, 0xef, 0xe1, 0xab, 0xf9, 0x0a, 0x3e, 0x87, 0x99, 0x99, 0x52,
	0x0b, 0x12, 0x37, 0xb8, 0x9b, 0x39, 0xe7, 0x9e, 0x3b, 0xf7, 0x9c, 0x9b, 0x01, 0xa0, 0x11, 0x0d,
	0x6d, 0x9a, 0x12, 0x46, 0x90, 0x91, 0x8d, 0xe7, 0x61, 0x1c, 0xb4, 0xcd, 0xd7, 0x60, 0x91, 0x17,
	0xa0, 0xf5, 0xa9, 0x80, 0x3e, 0x8c, 0x68, 0x88, 0x0e, 0x40, 0xf5, 0x1c, 0xac, 0x74, 0x94, 0x6e,
	0xd3, 0x57, 0x3d, 0x07, 0x5d, 0x41, 0x8b, 0x6b, 0x9d, 0x30, 0x1b, 0xa7, 0x11, 0x65, 0x24, 0xf5,
	0x1c, 0xac, 0x0a, 0xf6, 0x07, 0x8e, 0xae, 0xc1, 0xa0, 0x41, 0x1a, 0xc4, 0x19, 0xd6, 0x3a, 0x5a,
	0xd7, 0xec, 0x61, 0x5b, 0x3e, 0x65, 0xf3, 0xce, 0xf6, 0x50, 0x50, 0x6e, 0xc2, 0xd2, 0x95, 0x5f,
	0xd4, 0xa1, 0x73, 0xa8, 0x8d, 0xa2, 0x64, 0x92, 0x61, 0x5d, 0x08, 0x5a, 0x55, 0xc1, 0x20, 0x4a,
	0x26, 0xbe, 0xa4, 0xdb, 0x77, 0x60, 0x56, 0xe4, 0xa8, 0x05, 0xda, 0x4b, 0xb8, 0x2a, 0xa6, 0xe4,
	0x47, 0x74, 0x06, 0x35, 0x61, 0x47, 0xcc, 0x66, 0xf6, 0xfe, 0xaf, 0x1b, 0x3d, 0x71, 0xd0, 0x97,
	0xdc, 0xad, 0x7a, 0xa3, 0x58, 0x73, 0x68, 0xac, 0x9b, 0x23, 0x0b, 0xfe, 0x4d, 0x53, 0x12, 0x3f,
	0xe4, 0x8c, 0xe6, 0xac, 0x74, 0xbd, 0x81, 0xa1, 0x36, 0x34, 0x18, 0xe1, 0x8a, 0xd2, 0x77, 0x79,
	0x47, 0xa7, 0xd0, 0x64, 0xc4, 0x4b, 0xa4, 0x58, 0x13, 0xe4, 0x37, 0x60, 0x7d, 0xa8, 0x50, 0xe7,
	0x85, 0xee, 0x92, 0xed, 0x95, 0x6a, 0xbf, 0x4c, 0x55, 0x86, 0x74, 0x52, 0x0d, 0xc9, 0x5d, 0xb2,
	0x9d, 0xc1, 0x5e, 0xae, 0x83, 0xad, 0x09, 0xcd, 0xd1, 0x76, 0xb0, 0xee, 0x92, 0x15, 0xd9, 0x72,
	0x17, 0x74, 0x91, 0xcf, 0xa2, 0xe4, 0xd1, 0xf7, 0xb0, 0x21, 0x5d, 0x94, 0x00, 0x3a, 0x06, 0x63,
	0xba, 0x20, 0x6f, 0x9e, 0x83, 0xeb, 0x82, 0x2a, 0x6e, 0xc8, 0x06, 0xb4, 0x39, 0xe9, 0x7d, 0x10,
	0x87, 0xb8, 0x21, 0x6a, 0x76, 0x30, 0x7f, 0xb8, 0xc1, 0x77, 0x05, 0xcc, 0x8a, 0x8d, 0xbd, 0xb7,
	0x78, 0x01, 0x86, 0x3c, 0x63, 0x5d, 0xbc, 0x7c, 0xb8, 0x95, 0xaf, 0x5f, 0xd0, 0xbf, 0xaf, 0x7b,
	0x60, 0x3c, 0xeb, 0xb3, 0x80, 0x46, 0x23, 0x43, 0x7c, 0xa8, 0xfe, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x67, 0xb8, 0xb4, 0x4c, 0x73, 0x03, 0x00, 0x00,
}
