// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin_send_service.proto

package gapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMsgReq struct {
	Pipe                 *PipeExt        `protobuf:"bytes,1,opt,name=pipe,proto3" json:"pipe,omitempty"`
	InputId              string          `protobuf:"bytes,2,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	Message              map[string]*Any `protobuf:"bytes,3,rep,name=message,proto3" json:"message,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendMsgReq) Reset()         { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()    {}
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0962aae4cf65858, []int{0}
}

func (m *SendMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgReq.Unmarshal(m, b)
}
func (m *SendMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgReq.Marshal(b, m, deterministic)
}
func (m *SendMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgReq.Merge(m, src)
}
func (m *SendMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendMsgReq.Size(m)
}
func (m *SendMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgReq proto.InternalMessageInfo

func (m *SendMsgReq) GetPipe() *PipeExt {
	if m != nil {
		return m.Pipe
	}
	return nil
}

func (m *SendMsgReq) GetInputId() string {
	if m != nil {
		return m.InputId
	}
	return ""
}

func (m *SendMsgReq) GetMessage() map[string]*Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type SendMsgRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgRes) Reset()         { *m = SendMsgRes{} }
func (m *SendMsgRes) String() string { return proto.CompactTextString(m) }
func (*SendMsgRes) ProtoMessage()    {}
func (*SendMsgRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0962aae4cf65858, []int{1}
}

func (m *SendMsgRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgRes.Unmarshal(m, b)
}
func (m *SendMsgRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgRes.Marshal(b, m, deterministic)
}
func (m *SendMsgRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgRes.Merge(m, src)
}
func (m *SendMsgRes) XXX_Size() int {
	return xxx_messageInfo_SendMsgRes.Size(m)
}
func (m *SendMsgRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgRes.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendMsgReq)(nil), "schema.SendMsgReq")
	proto.RegisterMapType((map[string]*Any)(nil), "schema.SendMsgReq.MessageEntry")
	proto.RegisterType((*SendMsgRes)(nil), "schema.SendMsgRes")
}

func init() { proto.RegisterFile("plugin_send_service.proto", fileDescriptor_c0962aae4cf65858) }

var fileDescriptor_c0962aae4cf65858 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x94, 0xdb, 0x92, 0x90, 0x97, 0x22, 0xc0, 0x53, 0x9a, 0x85, 0x50, 0x96, 0x4c, 0x91, 0x08,
	0x0b, 0x65, 0x03, 0xa9, 0x42, 0x0c, 0x95, 0x2a, 0x77, 0x63, 0x89, 0x4c, 0xf3, 0x14, 0x2c, 0x1a,
	0xd7, 0xc4, 0x49, 0x45, 0x46, 0xfe, 0x90, 0x4f, 0x42, 0xb1, 0x1b, 0x51, 0xa9, 0x13, 0xdb, 0xf3,
	0xdd, 0xbd, 0x7b, 0xe7, 0x83, 0x89, 0xda, 0x34, 0x85, 0x90, 0x99, 0x46, 0x99, 0x67, 0x1a, 0xab,
	0x9d, 0x58, 0x63, 0xa2, 0xaa, 0x6d, 0xbd, 0xa5, 0x8e, 0x5e, 0xbf, 0x63, 0xc9, 0x43, 0x50, 0x42,
	0xed, 0xb1, 0xd0, 0xe3, 0xb2, 0xb5, 0xe3, 0xf4, 0x87, 0x00, 0xac, 0x50, 0xe6, 0x0b, 0x5d, 0x30,
	0xfc, 0xa4, 0x37, 0x30, 0xea, 0x74, 0x01, 0x89, 0x48, 0xec, 0xa7, 0xe7, 0x89, 0x5d, 0x4e, 0x96,
	0x42, 0xe1, 0xfc, 0xab, 0x66, 0x86, 0xa4, 0x13, 0x38, 0x15, 0x52, 0x35, 0x75, 0x26, 0xf2, 0x60,
	0x10, 0x91, 0xd8, 0x63, 0xae, 0x79, 0xbf, 0xe4, 0x74, 0x06, 0x6e, 0x89, 0x5a, 0xf3, 0x02, 0x83,
	0x61, 0x34, 0x8c, 0xfd, 0xf4, 0xaa, 0xb7, 0xf8, 0x3b, 0x92, 0x2c, 0xac, 0x62, 0x2e, 0xeb, 0xaa,
	0x65, 0xbd, 0x3e, 0x7c, 0x86, 0xf1, 0x21, 0x41, 0x2f, 0x60, 0xf8, 0x81, 0xad, 0x49, 0xe2, 0xb1,
	0x6e, 0xa4, 0xd7, 0x70, 0xb2, 0xe3, 0x9b, 0x06, 0xcd, 0x51, 0x3f, 0xf5, 0x7b, 0xeb, 0x47, 0xd9,
	0x32, 0xcb, 0x3c, 0x0c, 0xee, 0xc9, 0x74, 0x7c, 0xf0, 0x23, 0x9d, 0x7e, 0x13, 0xb8, 0x5c, 0x9a,
	0x76, 0x3a, 0x70, 0x65, 0xbb, 0xa1, 0xb7, 0xe0, 0xee, 0x35, 0x94, 0x1e, 0x27, 0x0c, 0x8f, 0x31,
	0x4d, 0x67, 0x70, 0x66, 0x1c, 0xea, 0x0a, 0x79, 0xf9, 0x8f, 0xc5, 0x98, 0x3c, 0x39, 0xaf, 0xa3,
	0x82, 0x2b, 0xf1, 0xe6, 0x98, 0xce, 0xef, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x72, 0x67,
	0xbf, 0xaf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginSendServiceClient is the client API for PluginSendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginSendServiceClient interface {
	SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRes, error)
	SendStreamMsg(ctx context.Context, opts ...grpc.CallOption) (PluginSendService_SendStreamMsgClient, error)
}

type pluginSendServiceClient struct {
	cc *grpc.ClientConn
}

func NewPluginSendServiceClient(cc *grpc.ClientConn) PluginSendServiceClient {
	return &pluginSendServiceClient{cc}
}

func (c *pluginSendServiceClient) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRes, error) {
	out := new(SendMsgRes)
	err := c.cc.Invoke(ctx, "/schema.PluginSendService/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginSendServiceClient) SendStreamMsg(ctx context.Context, opts ...grpc.CallOption) (PluginSendService_SendStreamMsgClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PluginSendService_serviceDesc.Streams[0], "/schema.PluginSendService/SendStreamMsg", opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginSendServiceSendStreamMsgClient{stream}
	return x, nil
}

type PluginSendService_SendStreamMsgClient interface {
	Send(*SendMsgReq) error
	CloseAndRecv() (*SendMsgRes, error)
	grpc.ClientStream
}

type pluginSendServiceSendStreamMsgClient struct {
	grpc.ClientStream
}

func (x *pluginSendServiceSendStreamMsgClient) Send(m *SendMsgReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pluginSendServiceSendStreamMsgClient) CloseAndRecv() (*SendMsgRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendMsgRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PluginSendServiceServer is the server API for PluginSendService service.
type PluginSendServiceServer interface {
	SendMsg(context.Context, *SendMsgReq) (*SendMsgRes, error)
	SendStreamMsg(PluginSendService_SendStreamMsgServer) error
}

// UnimplementedPluginSendServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPluginSendServiceServer struct {
}

func (*UnimplementedPluginSendServiceServer) SendMsg(ctx context.Context, req *SendMsgReq) (*SendMsgRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (*UnimplementedPluginSendServiceServer) SendStreamMsg(srv PluginSendService_SendStreamMsgServer) error {
	return status.Errorf(codes.Unimplemented, "method SendStreamMsg not implemented")
}

func RegisterPluginSendServiceServer(s *grpc.Server, srv PluginSendServiceServer) {
	s.RegisterService(&_PluginSendService_serviceDesc, srv)
}

func _PluginSendService_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginSendServiceServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.PluginSendService/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginSendServiceServer).SendMsg(ctx, req.(*SendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginSendService_SendStreamMsg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginSendServiceServer).SendStreamMsg(&pluginSendServiceSendStreamMsgServer{stream})
}

type PluginSendService_SendStreamMsgServer interface {
	SendAndClose(*SendMsgRes) error
	Recv() (*SendMsgReq, error)
	grpc.ServerStream
}

type pluginSendServiceSendStreamMsgServer struct {
	grpc.ServerStream
}

func (x *pluginSendServiceSendStreamMsgServer) SendAndClose(m *SendMsgRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pluginSendServiceSendStreamMsgServer) Recv() (*SendMsgReq, error) {
	m := new(SendMsgReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PluginSendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.PluginSendService",
	HandlerType: (*PluginSendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _PluginSendService_SendMsg_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStreamMsg",
			Handler:       _PluginSendService_SendStreamMsg_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "plugin_send_service.proto",
}
