// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package gapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Plugin struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string    `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PluginUri            string    `protobuf:"bytes,5,opt,name=plugin_uri,json=pluginUri,proto3" json:"plugin_uri,omitempty"`
	CreatedAt            *UnixTime `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *UnixTime `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Plugin) GetPluginUri() string {
	if m != nil {
		return m.PluginUri
	}
	return ""
}

func (m *Plugin) GetCreatedAt() *UnixTime {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Plugin) GetUpdatedAt() *UnixTime {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Plugin)(nil), "schema.Plugin")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x86, 0x49, 0xa9, 0x29, 0x3d, 0x8a, 0x4a, 0x16, 0x83, 0x20, 0x14, 0xa7, 0x4e, 0x15, 0xf4,
	0x09, 0xea, 0xe6, 0x26, 0xc5, 0x2e, 0x2e, 0x21, 0x36, 0xa1, 0x1e, 0x30, 0x69, 0x48, 0x13, 0xe8,
	0x13, 0xfa, 0x5c, 0x97, 0x26, 0xbd, 0xe3, 0xdd, 0x92, 0xff, 0xff, 0x3e, 0xce, 0x39, 0x70, 0xe3,
	0xfe, 0xe2, 0x8c, 0xb6, 0x73, 0x7e, 0x09, 0x0b, 0xa3, 0xeb, 0xf4, 0xab, 0x8d, 0x7c, 0xbc, 0x8b,
	0x16, 0x37, 0x11, 0xd0, 0xe8, 0x5c, 0x3c, 0xff, 0x13, 0xa0, 0x9f, 0x89, 0x64, 0xb7, 0x50, 0xa0,
	0xe2, 0xa4, 0x21, 0x6d, 0x3d, 0x14, 0xa8, 0x18, 0x83, 0xd2, 0x4a, 0xa3, 0x79, 0x91, 0x92, 0xf4,
	0x66, 0x0f, 0x50, 0xc5, 0x55, 0x7b, 0x81, 0x8a, 0x97, 0x29, 0xa6, 0xfb, 0xf7, 0x43, 0xb1, 0x27,
	0x80, 0x3c, 0x50, 0x44, 0x8f, 0xfc, 0x2a, 0x75, 0x75, 0x4e, 0x46, 0x8f, 0xec, 0x05, 0x60, 0xf2,
	0x5a, 0x06, 0xad, 0x84, 0x0c, 0x9c, 0x36, 0xa4, 0xbd, 0x7e, 0xbd, 0xef, 0xf2, 0x52, 0xdd, 0x68,
	0x71, 0xfb, 0x42, 0xa3, 0x87, 0xfa, 0x60, 0xfa, 0xb0, 0x0b, 0xd1, 0xa9, 0xb3, 0x50, 0x5d, 0x12,
	0x0e, 0xa6, 0x0f, 0xef, 0xf4, 0xbb, 0x9c, 0xa5, 0xc3, 0x1f, 0x9a, 0xee, 0x7a, 0x3b, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xdd, 0x72, 0x74, 0x95, 0x00, 0x01, 0x00, 0x00,
}
