// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unix-time.proto

package gapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnixTime struct {
	Sec                  int64    `protobuf:"varint,1,opt,name=sec,proto3" json:"sec,omitempty"`
	Nsec                 int64    `protobuf:"varint,2,opt,name=nsec,proto3" json:"nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnixTime) Reset()         { *m = UnixTime{} }
func (m *UnixTime) String() string { return proto.CompactTextString(m) }
func (*UnixTime) ProtoMessage()    {}
func (*UnixTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c3546e884ebd124, []int{0}
}

func (m *UnixTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnixTime.Unmarshal(m, b)
}
func (m *UnixTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnixTime.Marshal(b, m, deterministic)
}
func (m *UnixTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnixTime.Merge(m, src)
}
func (m *UnixTime) XXX_Size() int {
	return xxx_messageInfo_UnixTime.Size(m)
}
func (m *UnixTime) XXX_DiscardUnknown() {
	xxx_messageInfo_UnixTime.DiscardUnknown(m)
}

var xxx_messageInfo_UnixTime proto.InternalMessageInfo

func (m *UnixTime) GetSec() int64 {
	if m != nil {
		return m.Sec
	}
	return 0
}

func (m *UnixTime) GetNsec() int64 {
	if m != nil {
		return m.Nsec
	}
	return 0
}

func init() {
	proto.RegisterType((*UnixTime)(nil), "schema.UnixTime")
}

func init() { proto.RegisterFile("unix-time.proto", fileDescriptor_6c3546e884ebd124) }

var fileDescriptor_6c3546e884ebd124 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xcd, 0xcb, 0xac,
	0xd0, 0x2d, 0xc9, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4e, 0xce,
	0x48, 0xcd, 0x4d, 0x54, 0x32, 0xe0, 0xe2, 0x08, 0xcd, 0xcb, 0xac, 0x08, 0xc9, 0xcc, 0x4d, 0x15,
	0x12, 0xe0, 0x62, 0x2e, 0x4e, 0x4d, 0x96, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0x31, 0x85,
	0x84, 0xb8, 0x58, 0xf2, 0x40, 0x42, 0x4c, 0x60, 0x21, 0x30, 0xdb, 0x89, 0x2d, 0x8a, 0x25, 0x3d,
	0xb1, 0x20, 0x33, 0x89, 0x0d, 0x6c, 0x90, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x1c, 0xef,
	0x8a, 0x5b, 0x00, 0x00, 0x00,
}
