// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package gapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                *UserEmail   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string       `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt            *UnixTime    `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Profile              *UserProfile `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() *UserEmail {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetCreatedAt() *UnixTime {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UserEmail struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Verified             bool     `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEmail) Reset()         { *m = UserEmail{} }
func (m *UserEmail) String() string { return proto.CompactTextString(m) }
func (*UserEmail) ProtoMessage()    {}
func (*UserEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEmail.Unmarshal(m, b)
}
func (m *UserEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEmail.Marshal(b, m, deterministic)
}
func (m *UserEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEmail.Merge(m, src)
}
func (m *UserEmail) XXX_Size() int {
	return xxx_messageInfo_UserEmail.Size(m)
}
func (m *UserEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEmail.DiscardUnknown(m)
}

var xxx_messageInfo_UserEmail proto.InternalMessageInfo

func (m *UserEmail) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserEmail) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type UserProfile struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserProfile) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "schema.User")
	proto.RegisterType((*UserEmail)(nil), "schema.UserEmail")
	proto.RegisterType((*UserProfile)(nil), "schema.UserProfile")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4e, 0x84, 0x30,
	0x18, 0xc4, 0x03, 0x02, 0x0b, 0xdf, 0x26, 0xfe, 0xa9, 0x1e, 0x9a, 0xf5, 0xb2, 0xe1, 0xe2, 0x5e,
	0xc4, 0x44, 0x9f, 0x60, 0x8d, 0x5e, 0x8d, 0x21, 0x7a, 0xf1, 0x42, 0xea, 0xf6, 0xc3, 0xfd, 0x12,
	0x0a, 0xa4, 0x14, 0xb3, 0x2f, 0xe6, 0xfb, 0x19, 0x5a, 0x96, 0xb0, 0xc7, 0xe9, 0x4c, 0x7f, 0xd3,
	0x29, 0x40, 0xdf, 0xa1, 0xce, 0x5a, 0xdd, 0x98, 0x86, 0x45, 0xdd, 0x6e, 0x8f, 0x4a, 0xac, 0x2e,
	0xfa, 0x9a, 0x0e, 0x85, 0x21, 0x85, 0xce, 0x48, 0xff, 0x3c, 0x08, 0x3e, 0x3b, 0xd4, 0xec, 0x1c,
	0x7c, 0x92, 0xdc, 0x5b, 0x7b, 0x9b, 0x24, 0xf7, 0x49, 0xb2, 0x3b, 0x08, 0x51, 0x09, 0xaa, 0xb8,
	0xbf, 0xf6, 0x36, 0xcb, 0xc7, 0xab, 0xcc, 0x11, 0xb2, 0x21, 0xfc, 0x3a, 0x18, 0xb9, 0xf3, 0xd9,
	0x0d, 0x84, 0xed, 0xbe, 0xa9, 0x91, 0x87, 0xf6, 0xae, 0x13, 0xec, 0x01, 0x60, 0xa7, 0x51, 0x18,
	0x94, 0x85, 0x30, 0xfc, 0xcc, 0x32, 0x2e, 0x27, 0x46, 0x4d, 0x87, 0x0f, 0x52, 0x98, 0x27, 0x63,
	0x66, 0x6b, 0xd8, 0x3d, 0x2c, 0x5a, 0xdd, 0x94, 0x54, 0x21, 0x0f, 0x6c, 0xfa, 0x7a, 0xde, 0xf8,
	0xee, 0xac, 0xfc, 0x98, 0x49, 0xb7, 0x90, 0x4c, 0x2f, 0x61, 0x1c, 0x16, 0x42, 0x4a, 0x8d, 0x5d,
	0x37, 0x0e, 0x38, 0x4a, 0xb6, 0x82, 0xf8, 0x17, 0x35, 0x95, 0x84, 0xd2, 0x0e, 0x89, 0xf3, 0x49,
	0xa7, 0x2f, 0xb0, 0x9c, 0xa1, 0xd9, 0x2d, 0x24, 0x65, 0x5f, 0x55, 0x45, 0x2d, 0x14, 0x8e, 0x98,
	0x78, 0x38, 0x78, 0x13, 0x0a, 0xe7, 0x0d, 0xfe, 0x49, 0xc3, 0x73, 0xf4, 0x15, 0xfc, 0x88, 0x96,
	0xbe, 0x23, 0xfb, 0x9f, 0x4f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0xa4, 0x06, 0xed, 0x76,
	0x01, 0x00, 0x00,
}
