// Code generated by protoc-gen-go. DO NOT EDIT.
// source: value.proto

package gapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value_Type int32

const (
	Value_STRING  Value_Type = 0
	Value_UINT    Value_Type = 1
	Value_FLOAT   Value_Type = 2
	Value_BOOLEAN Value_Type = 3
)

var Value_Type_name = map[int32]string{
	0: "STRING",
	1: "UINT",
	2: "FLOAT",
	3: "BOOLEAN",
}

var Value_Type_value = map[string]int32{
	"STRING":  0,
	"UINT":    1,
	"FLOAT":   2,
	"BOOLEAN": 3,
}

func (x Value_Type) String() string {
	return proto.EnumName(Value_Type_name, int32(x))
}

func (Value_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6d8b663a521ecf69, []int{0, 0}
}

type Value struct {
	Type                 Value_Type `protobuf:"varint,1,opt,name=type,proto3,enum=schema.Value_Type" json:"type,omitempty"`
	Value                []byte     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d8b663a521ecf69, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetType() Value_Type {
	if m != nil {
		return m.Type
	}
	return Value_STRING
}

func (m *Value) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("schema.Value_Type", Value_Type_name, Value_Type_value)
	proto.RegisterType((*Value)(nil), "schema.Value")
}

func init() { proto.RegisterFile("value.proto", fileDescriptor_6d8b663a521ecf69) }

var fileDescriptor_6d8b663a521ecf69 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4b, 0xcc, 0x29,
	0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x54,
	0xaa, 0xe6, 0x62, 0x0d, 0x03, 0x09, 0x0b, 0xa9, 0x71, 0xb1, 0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x09, 0xe9, 0x41, 0xe4, 0xf5, 0xc0, 0x92, 0x7a, 0x21, 0x95, 0x05,
	0xa9, 0x41, 0x60, 0x79, 0x21, 0x11, 0x2e, 0x56, 0xb0, 0x39, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c,
	0x41, 0x10, 0x8e, 0x92, 0x09, 0x17, 0x0b, 0x48, 0x8d, 0x10, 0x17, 0x17, 0x5b, 0x70, 0x48, 0x90,
	0xa7, 0x9f, 0xbb, 0x00, 0x83, 0x10, 0x07, 0x17, 0x4b, 0xa8, 0xa7, 0x5f, 0x88, 0x00, 0xa3, 0x10,
	0x27, 0x17, 0xab, 0x9b, 0x8f, 0xbf, 0x63, 0x88, 0x00, 0x93, 0x10, 0x37, 0x17, 0xbb, 0x93, 0xbf,
	0xbf, 0x8f, 0xab, 0xa3, 0x9f, 0x00, 0xb3, 0x13, 0x5b, 0x14, 0x4b, 0x7a, 0x62, 0x41, 0x66, 0x12,
	0x1b, 0xd8, 0x4d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x17, 0x09, 0x19, 0xa2, 0x00,
	0x00, 0x00,
}
